### ISSUE TITLE
2.4.0 breaks GravityWiz's live merge tags in HTML fields

### ISSUE THREAD

**Issue by tufloc** [csalzano/power-boost-for-gravity-forms#15]
Hello.

The recent change you've made with 2.4.0 seems to break the use of  GravityWiz's [live merge tags](https://gravitywiz.com/documentation/gravity-forms-populate-anything/#live-merge-tags) in HTML fields.

The functionality worked fine using the previous version.

Any chance you could take a look at it, please?

Thanks.

**Comment by csalzano** [comment]
I think the fix is changing the priority 10 to 100 on this line: https://github.com/csalzano/power-boost-for-gravity-forms/blob/main/includes/html-field-merge-tags.php#L22

...but I'll test tomorrow to confirm. Thanks for the note!

**Comment by csalzano** [comment]
Fixed in 2.4.1

**Comment by tufloc** [comment]
I still see the same problem.

At 2.4.1.

**Comment by csalzano** [comment]
What are you seeing? I've got a live merge tag and a normal merge tag both working on the same form.

**Comment by tufloc** [comment]
[gravityforms-export-2022-08-09.json.txt](https://github.com/csalzano/power-boost-for-gravity-forms/files/9293421/gravityforms-export-2022-08-09.json.txt)

Here's a simple export file (remove .txt) for the form. Just a text field and an HTML field that is updated whenever the text field changes.

Works without boost.

**Comment by csalzano** [comment]
Thanks for this! I had an incorrect understanding of what Live Merge tags were. I think I've got this sorted in 2.4.2, a version I just pushed here. It's working for your test form. If you could give it a spin, I'd appreciate that.

**Comment by tufloc** [comment]
You managed to fix it on my sample form, but when you start to use more than one live merge tags in a field, the functionality once again breaks.

![image](https://user-images.githubusercontent.com/1139134/184018454-d08c45d0-b749-40fe-89a3-edae1bb6e050.png)

[gravityforms-export-2022-08-10.json.txt](https://github.com/csalzano/power-boost-for-gravity-forms/files/9303998/gravityforms-export-2022-08-10.json.txt)

Attaching an amended form showcasing the bug.

**Comment by csalzano** [comment]
Ah, I made a stupid mistake. Fixed in 2.4.3!

**Comment by tufloc** [comment]
Seems to work perfectly well now.
