### ISSUE TITLE
Also update gf-json when confimation/notifications are updated or created

### ISSUE THREAD

**Issue by Loosie94** [csalzano/power-boost-for-gravity-forms#26]
Hi, when I update an existing form notification, the JSON file inside gf-json is not updating. This only works when saving the form from inside the edit forms-fields screen. Can we add a hook that also stores this data once the settings, notifications or confirmations are saved? Thanks! :)

**Comment by csalzano** [comment]
Sure, I would consider this to be a bug. Thanks for the feedback.

**Comment by Loosie94** [comment]
@csalzano Thanks! Is this added in v3.1.8?

**Comment by csalzano** [comment]
3.1.7
 https://github.com/csalzano/power-boost-for-gravity-forms/releases/tag/v3.1.7
